In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

## Series

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj
# 第一列为索引，第二列为值

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3])

In [4]:
obj.value_counts()

 4    1
 7    1
-5    1
 3    1
dtype: int64

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
# 创建时指定索引
obj1 = pd.Series([4, 7, -5, 3], index=['a', 'b', 'c', 'd'])

In [7]:
obj1

a    4
b    7
c   -5
d    3
dtype: int64

In [8]:
# 使用标签对数据进行索引
obj1['a']

4

In [9]:
obj1[['b', 'd']]

b    7
d    3
dtype: int64

In [10]:
# 重新赋值
obj1['b'] = 99

In [11]:
obj1

a     4
b    99
c    -5
d     3
dtype: int64

In [12]:
obj1[obj1 > 0]

a     4
b    99
d     3
dtype: int64

In [13]:
obj1 * 2

a      8
b    198
c    -10
d      6
dtype: int64

In [14]:
np.exp(obj1)

a    5.459815e+01
b    9.889030e+42
c    6.737947e-03
d    2.008554e+01
dtype: float64

In [15]:
# 可以认为Series当作长度固定有序的字典
'b' in obj1

True

In [16]:
'e' in obj1

False

In [17]:
# 可以使用字典来生成一个Series
dict1 = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj2 = pd.Series(dict1)

In [18]:
obj2

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj3 = pd.Series(dict1, index=states)

In [20]:
obj3

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
pd.isnull(obj3)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
pd.notnull(obj3)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [23]:
# 数学操作中，会自动对其索引，与数据库的join操作非常类似
obj2 + obj3

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [24]:
# Series自身属性
obj3.name = 'population'
obj3.index.name = 'state'

In [25]:
obj3

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [26]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [27]:
# 通过按位索引的方式改变索引的值
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [28]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [29]:
pd.Series(['a', 'b', 'c', 'd'], index=[1, 2, 3, 4])

1    a
2    b
3    c
4    d
dtype: object

## Dataframe

In [30]:
# 可以使用列表或者字典来创建DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2001, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df = pd.DataFrame(data)

In [31]:
df

state  year  pop
0    Ohio  2001  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [32]:
# head方法只会挑选出前5行
df.head()

state  year  pop
0    Ohio  2001  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [33]:
# 如果指定的列不在原数据中，对应指定的列会显示为NaN
df2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])

In [34]:
df2

year   state  pop debt
one    2001    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [35]:
# 取出指定的列
df2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [36]:
# df2['state1'] 如果列不存在则会跑出错误

In [37]:
# df2.state1 # 同上

In [38]:
# 行也可以通过位置或特殊属性loc进行选取
df2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [39]:
# 列的引用是可以修改的，设置为标量值
df2.debt = 16.5

In [40]:
df2

year   state  pop  debt
one    2001    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [41]:
# 或者设置为值数组
df2.debt = np.arange(6)

In [42]:
df2

year   state  pop  debt
one    2001    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [43]:
# 当将Series赋值给DataFrame时，会按照索引重新排列，并在空缺的地方填充NaN
# 如果对应的列不存在，会新建一个列
series = pd.Series([1.2, -1.5, 1.7], index=['three', 'one', 'four'])
df2.debt = series
df2

year   state  pop  debt
one    2001    Ohio  1.5  -1.5
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   1.2
four   2001  Nevada  2.4   1.7
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN

In [44]:
df2['eastern'] = df2.state == 'Ohio'
#不能使用df2.eastern创建新的列

In [45]:
df2

year   state  pop  debt  eastern
one    2001    Ohio  1.5  -1.5     True
two    2001    Ohio  1.7   NaN     True
three  2002    Ohio  3.6   1.2     True
four   2001  Nevada  2.4   1.7    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2   NaN    False

In [46]:
# 字典嵌套的字典
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
df3 = pd.DataFrame(pop)

In [47]:
df3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [48]:
df3.index.name = 'year'
df3.columns.name = 'state'

In [49]:
df3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [50]:
# 转置
df3.T

year    2001  2002  2000
state                   
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [51]:
df3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [52]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [53]:
obj

a    0
b    1
c    2
dtype: int64

In [54]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [55]:
index[1:]

Index(['b', 'c'], dtype='object')

In [56]:
# 索引对象是不可变的，无法修改
#index[1]='e'
# TypeError: Index does not support mutable operations

In [57]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [58]:
obj4 = pd.Series([1.5, -2.5, 0], index=labels)
obj4

0    1.5
1   -2.5
2    0.0
dtype: float64

In [59]:
df3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [60]:
df3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [61]:
'Ohio' in df3.columns

True

In [62]:
2003 in df3.index

False

In [63]:
# pandas索引对象可以包含重复标签
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [64]:
dup_labels.append(pd.Index(['bar']))

Index(['foo', 'foo', 'bar', 'bar', 'bar'], dtype='object')

In [65]:
df3.index

Int64Index([2001, 2002, 2000], dtype='int64', name='year')

In [66]:
index1 = pd.Index(['cat', 'dog', 'pig', 'tiger'])
index2 = pd.Index(['cat', 'tiger'])
# 两个索引的差集
index1.difference(index2)

Index(['dog', 'pig'], dtype='object')

In [67]:
# 两个索引的交集
index1.intersection(index2)

Index(['cat', 'tiger'], dtype='object')

In [68]:
index1.delete(1)  # 删除其中的一个索引，传入的参数时索引的位置

Index(['cat', 'pig', 'tiger'], dtype='object')

In [69]:
index1.insert(1, 'horse')

Index(['cat', 'horse', 'dog', 'pig', 'tiger'], dtype='object')

In [70]:
# 重建索引
obj = pd.Series([4.5, 7.5, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.5
a   -5.3
c    3.6
dtype: float64

In [71]:
#会按照新的索引进行排序
obj.reindex(['a', 'b', 'c', 'd'])

a   -5.3
b    7.5
c    3.6
d    4.5
dtype: float64

In [72]:
# 如果新的索引没有对应的值，则填充NaN
obj.reindex(['a', 'b', 'c', 'd', 'e'])

a   -5.3
b    7.5
c    3.6
d    4.5
e    NaN
dtype: float64

In [73]:
# 部分索引
obj.reindex(['a', 'b'])

a   -5.3
b    7.5
dtype: float64

In [74]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [75]:
# 填充空置时，使用ffill时向前填充
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [76]:
frame = pd.DataFrame(np.arange(16).reshape(4, 4),
                     index=['a', 'b', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California', 'New York'])
frame

Ohio  Texas  California  New York
a     0      1           2         3
b     4      5           6         7
c     8      9          10        11
d    12     13          14        15

In [77]:
# 重建索引
frame.reindex(['a', 'b', 'c', 'd'])

Ohio  Texas  California  New York
a     0      1           2         3
b     4      5           6         7
c     8      9          10        11
d    12     13          14        15

In [78]:
state = ['Texas', 'Utah', 'California']
# 对于重建后的索引，如果原数据不包含新的索引，就会填充NaN
frame.reindex(columns=state)

Texas  Utah  California
a      1   NaN           2
b      5   NaN           6
c      9   NaN          10
d     13   NaN          14

In [79]:
frame

Ohio  Texas  California  New York
a     0      1           2         3
b     4      5           6         7
c     8      9          10        11
d    12     13          14        15

In [80]:
state = ['Texas', 'California']
# 使用loc必须保证给出的索引在DF中存在
frame.loc[['a', 'b', 'c', 'd'], state]

Texas  California
a      1           2
b      5           6
c      9          10
d     13          14

In [81]:
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [82]:
# 轴上删除条目
obj.drop('c')

a    0
b    1
d    3
e    4
dtype: int64

In [83]:
# 删除两个条目
obj.drop(['a', 'b'])

c    2
d    3
e    4
dtype: int64

In [84]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index=['Ohio', 'California', 'New York', 'Texas'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio          0    1      2     3
California    4    5      6     7
New York      8    9     10    11
Texas        12   13     14    15

In [85]:
# 删除行
data.drop('Ohio')

one  two  three  four
California    4    5      6     7
New York      8    9     10    11
Texas        12   13     14    15

In [86]:
# 删除列
data.drop(columns='one')

two  three  four
Ohio          1      2     3
California    5      6     7
New York      9     10    11
Texas        13     14    15

In [87]:
data.drop(['one', 'two'], axis='columns')

three  four
Ohio            2     3
California      6     7
New York       10    11
Texas          14    15

In [88]:
# drop操作不会修改原有Series或DataFrame的结构
# 如果直接操作原对象，则添加inplace
data.drop('Ohio', inplace=True)
data

one  two  three  four
California    4    5      6     7
New York      8    9     10    11
Texas        12   13     14    15

In [89]:
data.index
# Ohio已经从原DataFrame中被删除

Index(['California', 'New York', 'Texas'], dtype='object')

In [90]:
obj = pd.Series(np.arange(4), index=['a', 'b', 'c', 'd'])
obj

a    0
b    1
c    2
d    3
dtype: int64

In [91]:
obj[1:3]

b    1
c    2
dtype: int64

In [92]:
obj['b']

1

In [93]:
# 直接使用索引值进行切片，是包含尾部的
obj['b':'c']

b    1
c    2
dtype: int64

In [94]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index=['Ohio', 'California', 'NewYork', 'Washington'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio          0    1      2     3
California    4    5      6     7
NewYork       8    9     10    11
Washington   12   13     14    15

In [95]:
# 取出one这一列
data['one']

Ohio           0
California     4
NewYork        8
Washington    12
Name: one, dtype: int64

In [96]:
data[['one', 'three']]

one  three
Ohio          0      2
California    4      6
NewYork       8     10
Washington   12     14

In [97]:
data[:2]

one  two  three  four
Ohio          0    1      2     3
California    4    5      6     7

In [98]:
data[data['three'] > 5]

one  two  three  four
California    4    5      6     7
NewYork       8    9     10    11
Washington   12   13     14    15

In [99]:
# 布尔值可以通过与标量值比较产生
data < 5

one    two  three   four
Ohio         True   True   True   True
California   True  False  False  False
NewYork     False  False  False  False
Washington  False  False  False  False

### loc和iloc选择数据

In [100]:
# loc使用轴标签
# iloc使用整数标签
data.loc['California', ['one', 'two']]

one    4
two    5
Name: California, dtype: int64

In [101]:
data.loc[:'California', 'three']

Ohio          2
California    6
Name: three, dtype: int64

In [102]:
# 传入1,2，返回DataFrame的第1行
data.iloc[[1, 2]]

one  two  three  four
California    4    5      6     7
NewYork       8    9     10    11

In [103]:
# 传入第二个参数，返回指定列的内容
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: NewYork, dtype: int64

In [104]:
ser = pd.Series(np.arange(3.))
ser
#ser[-1] 会产生歧义

0    0.0
1    1.0
2    2.0
dtype: float64

In [105]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [106]:
ser2[-1]  # 使用给数字的索引则不会产生歧义

2.0

In [107]:
ser[:1]

0    0.0
dtype: float64

In [108]:
ser.iloc[:1]

0    0.0
dtype: float64

In [109]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

### 算数和数据对齐

In [111]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s1 + s2  # 相当于取并集

a    5.2
b    NaN
c    7.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [117]:
df1 = pd.DataFrame(np.arange(9.).reshape(3, 3),
                   index=['Ohio', 'Texas', 'California'],
                   columns=list('abc'))
df2 = pd.DataFrame(np.arange(12.).reshape(4, 3),
                   index=['Utah', 'Ohio', 'California', 'Texas'],
                   columns=list('bcd'))
df1

a    b    c
Ohio        0.0  1.0  2.0
Texas       3.0  4.0  5.0
California  6.0  7.0  8.0

In [118]:
df2

b     c     d
Utah        0.0   1.0   2.0
Ohio        3.0   4.0   5.0
California  6.0   7.0   8.0
Texas       9.0  10.0  11.0

In [119]:
df1 + df2  # 计算过后会自动对齐索引

a     b     c   d
California NaN  13.0  15.0 NaN
Ohio       NaN   4.0   6.0 NaN
Texas      NaN  13.0  15.0 NaN
Utah       NaN   NaN   NaN NaN

In [120]:
df1 - df2

a    b    c   d
California NaN  1.0  1.0 NaN
Ohio       NaN -2.0 -2.0 NaN
Texas      NaN -5.0 -5.0 NaN
Utah       NaN  NaN  NaN NaN

In [122]:
df1 = pd.DataFrame(np.arange(12.).reshape(3, 4),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape(4, 5),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [123]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [124]:
df1.add(df2, fill_value=0)  # 使用0来填充NaN

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [125]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [126]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [127]:
df1.div(1)  # 除以1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [128]:
df1.rdiv(1)  # 用1除以df1中的值，带上r就是参数反转

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [129]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### DataFrame与Series之间的操作

In [135]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
arr[0]

array([0, 1, 2, 3])

In [137]:
arr - arr[0]  # 每一行都减去第0列，这就是广播机制

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [138]:
frame = pd.DataFrame(np.arange(12).reshape(4, 3),
                     columns=list('abc'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

a   b   c
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11