## Numpy

In [1]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
% time for _ in range(10): my_arr2 = my_arr * 2

UsageError: Line magic function `%` not found.


In [3]:
% time for _ in range(10): my_list2 =[x * 2 for x in my_list]

UsageError: Line magic function `%` not found.


### ndarray 多维数组对象

In [4]:
data = np.random.randn(2, 3)
data

array([[-0.67661475,  0.11139964,  1.80394449],
       [ 0.32151213, -0.75642466, -0.42253258]])

In [5]:
data * 10

array([[-6.76614748,  1.11399645, 18.03944495],
       [ 3.21512132, -7.5642466 , -4.22532584]])

In [6]:
data + data

array([[-1.3532295 ,  0.22279929,  3.60788899],
       [ 0.64302426, -1.51284932, -0.84506517]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr1.shape

(5,)

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
# 会返回未初始化的垃圾数据
np.empty((2, 3, 2))

array([[[1.14405041e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11261027e-306, 1.31370903e-076]],

       [[7.12059668e-091, 1.72129261e+184],
        [1.00552135e-047, 9.95485984e-043],
        [3.99910963e+252, 4.04828584e-037]]])

In [19]:
arr3 = np.arange(15)

In [20]:
arr3.ndim

1

In [21]:
arr3.shape

(15,)

In [22]:
a = [x for x in range(10)]

In [23]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
np.asarray(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [26]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [27]:
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [29]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [30]:
float_arr = arr.astype(np.float64)

In [31]:
float_arr.dtype

dtype('float64')

In [32]:
arr = np.random.randn(2, 3)

In [33]:
arr

array([[-0.35577478,  1.26019327, -2.03609608],
       [ 2.06843498, -1.0804751 , -1.50964845]])

In [34]:
# float转int，小数点后的部分会被剔除
arr.astype(np.int32)

array([[ 0,  1, -2],
       [ 2, -1, -1]])

In [35]:
arr = np.array(['1.25', '0.96', '-2.34'], dtype=np.string_)

In [36]:
arr

array([b'1.25', b'0.96', b'-2.34'], dtype='|S5')

In [37]:
arr.dtype

dtype('S5')

In [38]:
arr.astype(np.float64)

array([ 1.25,  0.96, -2.34])

In [39]:
arr.dtype

dtype('S5')

In [40]:
int_array = np.arange(10)

In [41]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [43]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [46]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [47]:
# 带有标量计算的算术操作，会把计算参数传递给数组的每一个元素
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
arr2 = np.array([[1, 2, 4], [4, 1, 9]])

In [49]:
# 同尺寸数组之间的比较，会产生一个布尔值数组
arr2 > arr

array([[False, False,  True],
       [False, False,  True]])

In [50]:
arr3 = np.array([[1, 2, 3, 4], [6, 7, 8, 9]])

In [51]:
arr = np.arange(10)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[5]

5

In [54]:
arr[5:8]

array([5, 6, 7])

In [55]:
# 区别于Python的内建列表，数组的切片是原数组的视图。这意味着数据并不是被复制了，任何对于视图的修改都会反映到原数组上。
arr[5:8] = 12

In [56]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [57]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [58]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [59]:
# 不写切片值的[:]将会引用数组的所有值
arr_slice[:] = 64

In [60]:
arr_slice

array([64, 64, 64])

In [61]:
# 如果你还是想要一份数组切片的拷贝而不是一份视图的话，你就必须显式地复制这个数组，例如arr[5:8].copy()

In [62]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr2d[2]

array([7, 8, 9])

In [64]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr2d[0][0]

1

In [66]:
arr2d[2][2]

9

In [67]:
arr2d[1][2]

6

In [74]:
arr3d = np.array(
    [[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], [[13, 14, 51], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])

In [75]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 51],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [76]:
arr3d[0][1][2]

6

In [77]:
arr3d[1][1][2]

18

In [78]:
old_value = arr3d[0].copy()

In [79]:
arr3d[0] = 42

In [81]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42],
        [42, 42, 42],
        [42, 42, 42]],

       [[13, 14, 51],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [82]:
arr3d[0] = old_value

In [83]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 51],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [84]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [85]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [86]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [88]:
# 当然对切片表达式赋值时，整个切片都会重新赋值
arr2d[:2, 1:] = 0

In [90]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [91]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [92]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [93]:
data = np.random.rand(7, 4)

In [94]:
data

array([[0.06539654, 0.28863374, 0.75665072, 0.31110086],
       [0.54630776, 0.21859032, 0.69612161, 0.73549697],
       [0.37407407, 0.28872164, 0.27284145, 0.37832843],
       [0.267181  , 0.88829002, 0.00258763, 0.20526798],
       [0.06495923, 0.96963902, 0.98317636, 0.69141466],
       [0.19993989, 0.39910242, 0.25657381, 0.95642005],
       [0.75818567, 0.17604666, 0.07948241, 0.16167258]])

In [95]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [96]:
data[names == 'Bob']

array([[0.06539654, 0.28863374, 0.75665072, 0.31110086],
       [0.267181  , 0.88829002, 0.00258763, 0.20526798]])

In [97]:
data[names == 'Bob', 2:]

array([[0.75665072, 0.31110086],
       [0.00258763, 0.20526798]])

In [98]:
data[names == 'Bob', 3]

array([0.31110086, 0.20526798])

In [99]:
# ～符号可以在你想要对一个通用条件进行取反时使用
data[~(names == 'Bob')]

array([[0.54630776, 0.21859032, 0.69612161, 0.73549697],
       [0.37407407, 0.28872164, 0.27284145, 0.37832843],
       [0.06495923, 0.96963902, 0.98317636, 0.69141466],
       [0.19993989, 0.39910242, 0.25657381, 0.95642005],
       [0.75818567, 0.17604666, 0.07948241, 0.16167258]])

In [101]:
# 当要选择三个名字中的两个时，可以对多个布尔值条件进行联合，需要使用数学操作符如&（and）和|（or）
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [102]:
data[mask]

array([[0.06539654, 0.28863374, 0.75665072, 0.31110086],
       [0.37407407, 0.28872164, 0.27284145, 0.37832843],
       [0.267181  , 0.88829002, 0.00258763, 0.20526798],
       [0.06495923, 0.96963902, 0.98317636, 0.69141466]])

In [103]:
data

array([[0.06539654, 0.28863374, 0.75665072, 0.31110086],
       [0.54630776, 0.21859032, 0.69612161, 0.73549697],
       [0.37407407, 0.28872164, 0.27284145, 0.37832843],
       [0.267181  , 0.88829002, 0.00258763, 0.20526798],
       [0.06495923, 0.96963902, 0.98317636, 0.69141466],
       [0.19993989, 0.39910242, 0.25657381, 0.95642005],
       [0.75818567, 0.17604666, 0.07948241, 0.16167258]])

In [104]:
data[data < 0.5] = 0

In [105]:
data

array([[0.        , 0.        , 0.75665072, 0.        ],
       [0.54630776, 0.        , 0.69612161, 0.73549697],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.88829002, 0.        , 0.        ],
       [0.        , 0.96963902, 0.98317636, 0.69141466],
       [0.        , 0.        , 0.        , 0.95642005],
       [0.75818567, 0.        , 0.        , 0.        ]])

In [106]:
data[names != 'Bob'] = 7

In [107]:
data

array([[0.        , 0.        , 0.75665072, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.88829002, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ]])

In [ ]:
# 神奇索引
arr = np.empty((8, 4))
arr

In [ ]:
arr.shape[0]

In [ ]:
for i in range(arr.shape[0]):
    arr[i] = i

In [ ]:
arr

In [ ]:
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        arr[i][j] = i * j

In [ ]:
arr

In [ ]:
arr

In [ ]:
arr[[4, 3, 0, 6]]

In [ ]:
arr = np.arange(32).reshape((8, 4))

In [ ]:
arr

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
arr.T

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
arr = np.random.randn(6, 3)
arr

In [ ]:
np.dot(arr.T, arr)

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))

In [ ]:
arr

In [ ]:
arr.transpose((1, 0, 2))

In [ ]:
arr.transpose((2, 0, 1))

In [ ]:
arr

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))

In [ ]:
arr

In [ ]:
# swap axes返回的是数据的视图，而没有对数据进行复制
arr.swapaxes(1, 2)

In [ ]:
arr = np.arange(16)

In [ ]:
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
x = np.random.randn(8)
y = np.random.randn(8)
# 二元通用函数
np.maximum(x, y)

In [ ]:
arr = np.random.randn(7) * 5

In [ ]:
arr

In [ ]:
# 返回每个数据的小数和整数部分
reminder, whole_part = np.modf(arr)

In [ ]:
reminder

In [ ]:
whole_part

In [ ]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [ ]:
import matplotlib.pyplot as plt

plt.imshow(z, cmap=plt.cm.gray)
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2+y^2}$ for a grid of values")

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
# 这样会产生多个问题。首先，如果数组很大的话，速度会很慢（因为所有的工作都是通过解释器解释Python代码完成）
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

In [ ]:
result

In [ ]:
type(result)

In [ ]:
np.where(cond, xarr, yarr)

In [ ]:
arr = np.random.randn(4,4)
np.where(arr>0, 2, -2)

In [ ]:
np.where(arr>0, 2, arr)

In [ ]:
arr.mean()

In [ ]:
arr.sum()

In [ ]:
np.mean(arr)

In [ ]:
np.mean([1,2,3,4])

In [ ]:
arr.mean(axis=1)

In [ ]:
arr.mean(axis=0)

In [ ]:
arr.mean(1)

In [ ]:
arr.mean(0)

In [ ]:
arr = np.arange(8)
arr

In [ ]:
arr.cumsum()

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

In [ ]:
arr.cumsum(axis=1)

In [ ]:
arr.cumprod(axis=1)

In [187]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [188]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [189]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [190]:
arr.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [191]:
arr.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)