In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.DataFrame([[1., 6.5, 3.0], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.0]])
data

0    1    2
0  1.0  6.5  3.0
1  NaN  NaN  NaN
2  NaN  6.5  3.0

In [4]:
data.dropna(axis=0, how='all')

0    1    2
0  1.0  6.5  3.0
2  NaN  6.5  3.0

In [5]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  NaN  NaN  NaN
2  NaN  6.5  3.0

In [7]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df

0         1         2
0 -0.445954 -0.571479 -0.606698
1  1.339539  0.269366  0.925504
2  0.618872 -0.962739  1.253893
3  0.818340 -0.701520 -0.132058
4 -1.144030 -2.830691 -1.516567
5  0.180182 -0.676271 -0.097487
6  0.850881 -0.636811 -0.583710

In [8]:
df.iloc[:4, 1] = np.nan

In [9]:
df.iloc[:2, 2] = np.nan

In [10]:
df

0         1         2
0 -0.445954       NaN       NaN
1  1.339539       NaN       NaN
2  0.618872       NaN  1.253893
3  0.818340       NaN -0.132058
4 -1.144030 -2.830691 -1.516567
5  0.180182 -0.676271 -0.097487
6  0.850881 -0.636811 -0.583710

In [11]:
df.dropna(axis=0, thresh=2)

0         1         2
2  0.618872       NaN  1.253893
3  0.818340       NaN -0.132058
4 -1.144030 -2.830691 -1.516567
5  0.180182 -0.676271 -0.097487
6  0.850881 -0.636811 -0.583710

In [12]:
df.dropna()

0         1         2
4 -1.144030 -2.830691 -1.516567
5  0.180182 -0.676271 -0.097487
6  0.850881 -0.636811 -0.583710

In [13]:
df

0         1         2
0 -0.445954       NaN       NaN
1  1.339539       NaN       NaN
2  0.618872       NaN  1.253893
3  0.818340       NaN -0.132058
4 -1.144030 -2.830691 -1.516567
5  0.180182 -0.676271 -0.097487
6  0.850881 -0.636811 -0.583710

In [14]:
df.fillna(0)

0         1         2
0 -0.445954  0.000000  0.000000
1  1.339539  0.000000  0.000000
2  0.618872  0.000000  1.253893
3  0.818340  0.000000 -0.132058
4 -1.144030 -2.830691 -1.516567
5  0.180182 -0.676271 -0.097487
6  0.850881 -0.636811 -0.583710

In [15]:
df.fillna({1: 0.5, 2: 0.25})

0         1         2
0 -0.445954  0.500000  0.250000
1  1.339539  0.500000  0.250000
2  0.618872  0.500000  1.253893
3  0.818340  0.500000 -0.132058
4 -1.144030 -2.830691 -1.516567
5  0.180182 -0.676271 -0.097487
6  0.850881 -0.636811 -0.583710

In [16]:
df

0         1         2
0 -0.445954       NaN       NaN
1  1.339539       NaN       NaN
2  0.618872       NaN  1.253893
3  0.818340       NaN -0.132058
4 -1.144030 -2.830691 -1.516567
5  0.180182 -0.676271 -0.097487
6  0.850881 -0.636811 -0.583710

In [17]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [19]:
# 分箱
ages = [22, 21, 25, 27, 31, 99, 80, 45, 41, 35, 32, 18]
cate = pd.cut(ages, bins=[15, 25, 35, 60, 100])

In [21]:
cate.value_counts()

(15, 25]     4
(25, 35]     4
(35, 60]     2
(60, 100]    2
Name: count, dtype: int64

In [22]:
cate.codes

array([0, 0, 0, 1, 1, 3, 3, 2, 2, 1, 1, 0], dtype=int8)

In [23]:
cate1 = pd.cut(ages, bins=[15, 25, 35, 60, 100], right=False)

In [24]:
cate1

[[15, 25), [15, 25), [25, 35), [25, 35), [25, 35), ..., [35, 60), [35, 60), [35, 60), [25, 35), [15, 25)]
Length: 12
Categories (4, interval[int64, left]): [[15, 25) < [25, 35) < [35, 60) < [60, 100)]

In [25]:
cate1.value_counts()

[15, 25)     3
[25, 35)     4
[35, 60)     3
[60, 100)    2
Name: count, dtype: int64

In [27]:
group_label = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
cate2 = pd.cut(ages, bins=[15, 25, 35, 60, 100], labels=group_label)

In [28]:
cate2.value_counts()

Youth         4
YoungAdult    4
MiddleAged    2
Senior        2
Name: count, dtype: int64

In [30]:
data = np.random.uniform(size=20)
data

array([0.9934426 , 0.23532606, 0.63056794, 0.18815903, 0.29114296,
       0.79320105, 0.02724611, 0.74472786, 0.28622077, 0.11973929,
       0.72392892, 0.36668995, 0.18014957, 0.68910932, 0.75907981,
       0.09261751, 0.41362927, 0.63162065, 0.6201629 , 0.18778531])

In [32]:
cate = pd.cut(data, 4, precision=2)

In [33]:
cate

[(0.75, 0.99], (0.026, 0.27], (0.51, 0.75], (0.026, 0.27], (0.27, 0.51], ..., (0.026, 0.27], (0.27, 0.51], (0.51, 0.75], (0.51, 0.75], (0.026, 0.27]]
Length: 20
Categories (4, interval[float64, right]): [(0.026, 0.27] < (0.27, 0.51] < (0.51, 0.75] < (0.75, 0.99]]

In [34]:
cate.value_counts()

(0.026, 0.27]    7
(0.27, 0.51]     4
(0.51, 0.75]     6
(0.75, 0.99]     3
Name: count, dtype: int64

In [35]:
cate = pd.qcut(data, q=2, labels=False)

In [38]:
cate

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0])

In [39]:
data = np.random.uniform(size=1000)
quartiles = pd.qcut(data, 4, precision=2)

In [40]:
quartiles.value_counts()

(-0.00973, 0.27]    250
(0.27, 0.51]        250
(0.51, 0.76]        250
(0.76, 1.0]         250
Name: count, dtype: int64

In [41]:
# 传递自定义分位数
pd.qcut(data, [0, 0.2, 0.5, 0.9, 1.], precision=2).value_counts()

(-0.00973, 0.22]    200
(0.22, 0.51]        300
(0.51, 0.9]         400
(0.9, 1.0]          100
Name: count, dtype: int64

In [42]:
sample = np.random.permutation(5)
sample

array([4, 1, 0, 3, 2])

In [43]:
data = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
data

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [44]:
data.take(sample)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [53]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], "data1": np.arange(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [56]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [59]:
df[["data1"]]

data1
0      0
1      1
2      2
3      3
4      4
5      5

In [61]:
df[['data1']].join(dummies)

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [62]:
type(df["data1"])

pandas.core.series.Series

In [65]:
type(df[["data1"]])

pandas.core.frame.DataFrame

In [68]:
data = pd.read_table("../dataset/examples/movies.dat", header=None, names=["movie_id", "title", "genres"],
                     engine="python", sep="::")

In [69]:
data.head()

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [70]:
data["genres"].head()

0     Animation|Children's|Comedy
1    Adventure|Children's|Fantasy
2                  Comedy|Romance
3                    Comedy|Drama
4                          Comedy
Name: genres, dtype: object

In [72]:
data["genres"].str.get_dummies("|")

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0          0          0          1           1       1      0            0   
1          0          1          0           1       0      0            0   
2          0          0          0           0       1      0            0   
3          0          0          0           0       1      0            0   
4          0          0          0           0       1      0            0   
...      ...        ...        ...         ...     ...    ...          ...   
3878       0          0          0           0       1      0            0   
3879       0          0          0           0       0      0            0   
3880       0          0          0           0       0      0            0   
3881       0          0          0           0       0      0            0   
3882       0          0          0           0       0      0            0   

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0         0        0          0       0        0        0        0       0   
1         0        1          0       0        0        0        0       0   
2         0        0          0       0        0        0        1       0   
3         1        0          0       0        0        0        0       0   
4         0        0          0       0        0        0        0       0   
...     ...      ...        ...     ...      ...      ...      ...     ...   
3878      0        0          0       0        0        0        0       0   
3879      1        0          0       0        0        0        0       0   
3880      1        0          0       0        0        0        0       0   
3881      1        0          0       0        0        0        0       0   
3882      1        0          0       0        0        0        0       0   

      Thriller  War  Western  
0            0    0        0  
1            0    0        0  
2            0    0        0  
3            0    0        0  
4            0    0        0  
...        ...  ...      ...  
3878         0    0        0  
3879         0    0        0  
3880         0    0        0  
3881         0    0        0  
3882         1    0        0  

[3883 rows x 18 columns]