In [1]:
import numpy as np
import pandas as pd
from sympy.polys.polytools import named_poly

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [5]:
# 创建带有索引的Series
obj_index = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj_index

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj_index[obj_index > 0]

d    4
b    7
c    3
dtype: int64

In [7]:
import numpy as np

np.exp(obj_index)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [8]:
# 通过字典来创建Series
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [9]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [10]:
state = ['California', "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=state)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [11]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [12]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [13]:
# DataFrame
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [14]:
frame['year']

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [15]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [16]:
frame.loc[1]

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

In [17]:
frame.iloc[1]

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

In [18]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [19]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 3.9}}
frame3 = pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     3.9

In [20]:
frame3.index.name = "year"

In [21]:
frame3

Ohio  Nevada
year              
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     3.9

In [22]:
frame.index.name = "state"

In [23]:
frame3

Ohio  Nevada
year              
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     3.9

In [24]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 3.9]])

In [36]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
obj

a    0
b    1
c    2
dtype: int64

In [37]:
index = obj.index

In [38]:
index

Index(['a', 'b', 'c'], dtype='object')

In [39]:
index[:1]

Index(['a'], dtype='object')

In [40]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["One", "Two", "Three", "Four"])
data

One  Two  Three  Four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [41]:
data.drop(index=['Colorado', "Utah"])

One  Two  Three  Four
Ohio        0    1      2     3
New York   12   13     14    15

In [42]:
data.drop(columns=['Two', "Three"])

One  Four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

In [43]:
data

One  Two  Three  Four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [44]:
data['Two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: Two, dtype: int64

In [48]:
data.loc['Utah']

One       8
Two       9
Three    10
Four     11
Name: Utah, dtype: int64

In [47]:
data.index[1]

'Colorado'

In [46]:
data

One  Two  Three  Four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [47]:
data.iloc[1]

One      4
Two      5
Three    6
Four     7
Name: Colorado, dtype: int64

In [51]:
data.index.name = "state"

In [52]:
data

One  Two  Three  Four
state                          
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [53]:
data.index.name

'state'

In [60]:
data[:2]

One  Two  Three  Four
state                          
Ohio        0    1      2     3
Colorado    4    5      6     7

In [61]:
data.loc['Colorado']

One      4
Two      5
Three    6
Four     7
Name: Colorado, dtype: int64

In [67]:
data.loc["Colorado", 'Two']

5

In [49]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [50]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [51]:
ser2.loc['a']

0.0

In [52]:
ser2.iloc[1]

1.0

In [53]:
ser2.iloc[-1]

2.0

In [54]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [55]:
ser2.iloc[-1]

2.0

In [58]:
type(ser2.iloc[-1])

numpy.float64

In [59]:
ser2[:2]

a    0.0
b    1.0
dtype: float64

In [60]:
data

One  Two  Three  Four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [61]:
data.loc[:, "One"]

Ohio         0
Colorado     4
Utah         8
New York    12
Name: One, dtype: int64

In [62]:
data['One']

Ohio         0
Colorado     4
Utah         8
New York    12
Name: One, dtype: int64

In [63]:
data.iloc[2] = 5

In [64]:
data

One  Two  Three  Four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        5    5      5     5
New York   12   13     14    15

In [65]:
data.iloc[2]

One      5
Two      5
Three    5
Four     5
Name: Utah, dtype: int64

In [66]:
data.loc[data['Four'] > 5]

One  Two  Three  Four
Colorado    4    5      6     7
New York   12   13     14    15

In [67]:
data.loc[data['Four'] > 5] = 3

In [68]:
data

One  Two  Three  Four
Ohio        0    1      2     3
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [69]:
data.loc[data.Three == 5]['Three']

Utah    5
Name: Three, dtype: int64

In [70]:
data.loc[data.Three == 5]

One  Two  Three  Four
Utah    5    5      5     5

In [71]:
data.loc['Utah']

One      5
Two      5
Three    5
Four     5
Name: Utah, dtype: int64

In [78]:
data.loc[data.Three == 5, 'Three'] = 6

In [79]:
data

One  Two  Three  Four
Ohio        0    1      2     3
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

In [80]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [82]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [83]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [84]:
df1 = pd.DataFrame(np.arange(9).reshape(3, 3), columns=list("bcd"), index=['Ohio', 'Texas', "Colorado"])
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [85]:
df2 = pd.DataFrame(np.arange(12).reshape((4, 3)), columns=list("bde"), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [86]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [87]:
df1.add(df2, fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [88]:
1 / df1

b         c      d
Ohio           inf  1.000000  0.500
Texas     0.333333  0.250000  0.200
Colorado  0.166667  0.142857  0.125

In [89]:
df1.rdiv(1)

b         c      d
Ohio           inf  1.000000  0.500
Texas     0.333333  0.250000  0.200
Colorado  0.166667  0.142857  0.125

In [90]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [91]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [92]:
df1.reindex(columns=df2.columns, fill_value=0)

b  d  e
Ohio      0  2  0
Texas     3  5  0
Colorado  6  8  0

In [93]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [94]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [95]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [97]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [98]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [99]:
series2 = pd.Series(np.arange(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [100]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [101]:
series2

b    0
e    1
f    2
dtype: int64

In [102]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [103]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [107]:
frame + series3

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [108]:
frame.add(series3, axis='index')

b     d     e
Utah     1.0   2.0   3.0
Ohio     7.0   8.0   9.0
Texas   13.0  14.0  15.0
Oregon  19.0  20.0  21.0

In [109]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [110]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [111]:
frame1 = pd.DataFrame(np.random.standard_normal((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame1

b         d         e
Utah   -0.310184  1.139091 -1.674439
Ohio    2.281794  0.972248  1.765131
Texas  -0.799112 -1.317864  0.162261
Oregon  0.143093  0.753063 -0.120219

In [112]:
np.abs(frame1)

b         d         e
Utah    0.310184  1.139091  1.674439
Ohio    2.281794  0.972248  1.765131
Texas   0.799112  1.317864  0.162261
Oregon  0.143093  0.753063  0.120219

In [113]:
def f1(x):
    return x.max() - x.min()


In [114]:
frame1.apply(f1)

b    3.080906
d    2.456955
e    3.439569
dtype: float64

In [115]:
frame1.apply(f1, axis=1)

Utah      2.813530
Ohio      1.309546
Texas     1.480125
Oregon    0.873281
dtype: float64

In [116]:
frame1.apply(f1, axis=0)

b    3.080906
d    2.456955
e    3.439569
dtype: float64

In [117]:
frame1.apply(f1, axis='columns')

Utah      2.813530
Ohio      1.309546
Texas     1.480125
Oregon    0.873281
dtype: float64

In [119]:
a = frame1.apply(f1, axis='columns')

In [122]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [123]:
frame1.apply(f2, axis='columns')

min       max
Utah   -1.674439  1.139091
Ohio    0.972248  2.281794
Texas  -1.317864  0.162261
Oregon -0.120219  0.753063

In [124]:
frame1.apply(f2)

b         d         e
min -0.799112 -1.317864 -1.674439
max  2.281794  1.139091  1.765131

In [125]:
def my_format(x):
    return f"{x:.2f}"

In [128]:
frame1.map(my_format)

b      d      e
Utah    -0.31   1.14  -1.67
Ohio     2.28   0.97   1.77
Texas   -0.80  -1.32   0.16
Oregon   0.14   0.75  -0.12

In [129]:
frame1['e'].map(my_format)

Utah      -1.67
Ohio       1.77
Texas      0.16
Oregon    -0.12
Name: e, dtype: object

In [130]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [131]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [132]:
obj.rank()

d    1.0
a    2.0
b    3.0
c    4.0
dtype: float64

In [133]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])

In [134]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [135]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [136]:
frame.sort_index(axis='columns')

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [137]:
frame.sort_index(axis='columns', ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [143]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [144]:
frame.sort_values(by='a', ascending=False)

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [145]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [147]:
obj.sort_values(na_position='last')

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [148]:
obj.sort_values(na_position='first')

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [149]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [151]:
frame.sort_values('b', ascending=False)

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [152]:
obj.rank()

0    3.0
1    NaN
2    4.0
3    NaN
4    1.0
5    2.0
dtype: float64

In [153]:
obj.rank(method='first')

0    3.0
1    NaN
2    4.0
3    NaN
4    1.0
5    2.0
dtype: float64

In [156]:
obj.rank(method='first')

0    3.0
1    NaN
2    4.0
3    NaN
4    1.0
5    2.0
dtype: float64

In [157]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [158]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [159]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [160]:
obj.rank(method='dense')

0    5.0
1    1.0
2    5.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64

In [161]:
obj = pd.Series(np.arange(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [162]:
obj.loc['a']

a    0
a    1
dtype: int64

In [164]:
obj.index.is_unique

False

In [165]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [167]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [168]:
df.sum(axis=0)

one    9.25
two   -5.80
dtype: float64

In [169]:
df.mean(axis=1)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [171]:
df.mean()

one    3.083333
two   -2.900000
dtype: float64

In [172]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [173]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [174]:
df.quantile(0.5)

one    1.4
two   -2.9
Name: 0.5, dtype: float64

In [175]:
# 股票价格
price = pd.read_pickle("/Users/summer/PycharmProjects/LearningPython/dataset/yahoo_price.pkl")
# 成交量
volume = pd.read_pickle("/Users/summer/PycharmProjects/LearningPython/dataset/yahoo_volume.pkl")

In [176]:
returns = price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [177]:
price.head()

AAPL        GOOG         IBM       MSFT
Date                                                    
2010-01-04  27.990226  313.062468  113.304536  25.884104
2010-01-05  28.038618  311.683844  111.935822  25.892466
2010-01-06  27.592626  303.826685  111.208683  25.733566
2010-01-07  27.541619  296.753749  110.823732  25.465944
2010-01-08  27.724725  300.709808  111.935822  25.641571

In [178]:
volume.head()

AAPL      GOOG      IBM      MSFT
Date                                              
2010-01-04  123432400   3927000  6155300  38409100
2010-01-05  150476200   6031900  6841400  49749600
2010-01-06  138040000   7987100  5605300  58182400
2010-01-07  119282800  12876600  5840600  50559700
2010-01-08  111902700   9483900  4197200  51197400

In [179]:
returns['MSFT'].corr(returns['IBM'])

0.49976361144151155

In [180]:
returns['MSFT'].cov(returns['IBM'])

8.870655479703546e-05

In [183]:
returns['MSFT'].corr(returns['AAPL'])

0.3896945862805784

In [184]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [186]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [187]:
obj = pd.Series(['c','a','b','a','a','b','b','c','c'])
obj

0    c
1    a
2    b
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [188]:
obj.nunique()

3

In [189]:
obj.unique()

array(['c', 'a', 'b'], dtype=object)

In [190]:
obj.value_counts()

c    3
a    3
b    3
Name: count, dtype: int64

In [191]:
to_match = pd.Series(['c','a','b','b','c','a'])

In [192]:
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [194]:
unique_vals = pd.Series(['c','b','a'])
unique_vals

0    c
1    b
2    a
dtype: object

In [195]:
indices = pd.Index(unique_vals).get_indexer(to_match)

In [196]:
indices

array([0, 2, 1, 1, 0, 2])